# Generated by Django 2.2.6 on 2019-10-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('SP', 'São Paulo'), ('---', '---')], max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
