# Generated by Django 2.2.6 on 2019-10-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='estado',
            field=models.CharField(choices=[('---', '---'), ('SP', 'São Paulo')], max_length=255),
        ),
    ]
