# Generated by Django 2.2.6 on 2019-10-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doador', '0001_initial'),
        ('escola', '0002_auto_20191021_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('doador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doador.Doador')),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escola.Escola')),
            ],
        ),
    ]
