# Generated by Django 2.2.6 on 2019-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='idade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doador',
            name='telefone',
            field=models.CharField(max_length=255),
        ),
    ]
